const fs = require('fs');
let code = fs.readFileSync('src/main.ts', 'utf8');
code = code.replace(/const TECH_DOMAIN_ORDER[\s\S]*?\];/g, '');
code = code.replace(/function techDomainLabel[\s\S]*?\n\}/g, '');
code = code.replace(/function techStatusLabel[\s\S]*?\n\}/g, '');
code = code.replace(/let isGovernmentFormDirty = false;/g, '');
code = code.replace(/let hideCompletedTechnologies = true;/g, '');
code = code.replace(/let lastCandidatePoolHash = "";/g, '');
code = code.replace(/function isGovernmentInputFocused\(\)[\s\S]*?\n    \}/g, '');
code = code.replace(/ui\.governmentApplyButton\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.expansionAutomationSelect\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.constructionAutomationSelect\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.globalAutomationToggle\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.techFocusSelect\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.techAutomationSelect\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.techHideCompletedToggle\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.techClearGoalButton\.addEventListener\([\s\S]*?\n    \}\);/g, '');
code = code.replace(/ui\.techApplyButton\.addEventListener\([\s\S]*?\n    \}\);/g, '');
fs.writeFileSync('src/main.ts', code);

