import React, { createContext, useContext, useEffect, useState, useRef } from 'react';
import { AppState } from 'react-native';
import { GameSession } from '../application/game-session';
import { createStaticWorldData } from '../application/boot/static-world-data';
import { WORLD_DEFINITIONS_V1, WORLD_DEFINITIONS_MAP_ID } from '../application/boot/generated/world-definitions-v1';
import { createInitialState } from '../application/boot/create-initial-state';
import { LocalEventBus } from '../infrastructure/runtime/local-event-bus';
import { UtilityNpcDecisionService } from '../infrastructure/npc/utility-npc-decision-service';
import { LocalDiplomacyResolver } from '../infrastructure/diplomacy/local-diplomacy-resolver';
import { LocalWarResolver } from '../infrastructure/war/local-war-resolver';
import { createDefaultSimulationSystems } from '../core/simulation/create-default-systems';
import { GameState } from '../core/models/game-state';
import { ClockService } from '../core/contracts/services';
import { AILogger } from '../infrastructure/telemetry/AILogger';

import { 
  MemoryCommandLogRepository, 
  MemorySnapshotRepository 
} from './memory-persistence';
import { MobileGameStateRepository, MobileSaveRepository } from '../infrastructure/persistence/MobileGameStateRepository';

class NativeClockService implements ClockService {
  private intervalId: ReturnType<typeof setInterval> | null = null;
  private lastTickAt = 0;
  private listeners: ((deltaMs: number, now: number) => void)[] = [];

  start(onTick: (deltaMs: number, now: number) => void) {
    this.stop();
    this.lastTickAt = this.now();
    this.intervalId = setInterval(() => {
      const now = this.now();
      const deltaMs = Math.max(1, now - this.lastTickAt);
      this.lastTickAt = now;
      onTick(deltaMs, now);
    }, 1000);
  }

  stop() {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }

  now(): number {
    return Date.now();
  }
}

interface GameContextData {
  gameState: GameState | null;
  session: GameSession | null;
  playerKingdomId: string;
  staticWorldData: any;
}

const GameContext = createContext<GameContextData>({
  gameState: null,
  session: null,
  playerKingdomId: "PLAYER_KINGDOM",
  staticWorldData: null,
});

export const useGameState = () => useContext(GameContext);

export function GameProvider({ children }: { children: React.ReactNode }) {
  const [session, setSession] = useState<GameSession | null>(null);
  const [gameState, setGameState] = useState<GameState | null>(null);
  const [staticWorldData] = useState(() => createStaticWorldData(WORLD_DEFINITIONS_V1, WORLD_DEFINITIONS_MAP_ID));
  const playerKingdomId = 'k_player'; // The ID generated by createInitialState for the player

  useEffect(() => {
    // Initialize Game Engine
    const eventBus = new LocalEventBus();
    const npcDecisionService = new UtilityNpcDecisionService(staticWorldData);
    const diplomacyResolver = new LocalDiplomacyResolver();
    const warResolver = new LocalWarResolver(staticWorldData);
    const clock = new NativeClockService();

    const newSession = new GameSession({
      gameStateRepository: new MobileGameStateRepository(),
      saveRepository: new MobileSaveRepository(),
      commandLogRepository: new MemoryCommandLogRepository(),
      snapshotRepository: new MemorySnapshotRepository(),
      staticWorldData,
      clock,
      eventBus,
      systems: createDefaultSimulationSystems({
        staticData: staticWorldData,
        orderedDefinitions: WORLD_DEFINITIONS_V1,
        npcDecisionService,
        diplomacyResolver,
        warResolver,
        eventBus
      }),
      diplomacyResolver,
      warResolver,
    });

    const initGame = async () => {
      try {
        AILogger.init();
        
        // Start a new campaign for prototype
        const initialState = createInitialState(staticWorldData, undefined, WORLD_DEFINITIONS_V1);
        await newSession.bootstrap(initialState);

      // Subscribe to React state updates
      newSession.subscribe((newState) => {
        // We MUST shallow clone the state, otherwise React ignores the update because the Engine mutates the object in-place!
        setGameState({ ...newState });
      });

      // Since we run synchronously on mobile (no Web Worker yet), we instantly mark the worker as ready.
      newSession.markWorkerReady();

      // Force first state grab
      const startingState = newSession.getState();
      setGameState({ ...startingState });
      setSession(newSession);

      // Log the initial fully loaded state to the AI, then disable auto-log to save CPU
      AILogger.logStateDump(startingState, true).finally(() => {
        AILogger.disableAutoLog();
      });

      // Start engine tick
      newSession.start();
      } catch (e) {
        console.error("Error bootstrapping game session:", e);
      }
    };

    initGame();

    const subscription = AppState.addEventListener('change', (nextAppState) => {
      if (nextAppState.match(/inactive|background/)) {
        console.log('[GameProvider] App going to background. Forcing save to disk.');
        newSession.forceSaveToDisk();
      }
    });

    return () => {
      subscription.remove();
      newSession.stop();
    };
  }, []);

  return (
    <GameContext.Provider value={{ 
      gameState, 
      session, 
      playerKingdomId: "k_player",
      staticWorldData 
    }}>
      {children}
    </GameContext.Provider>
  );
}
